version: '3.3'
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
  pets-api:
    image: pets-api:latest
    environment:
      - DATABASE_URL=mysql://root:password@db:3306/db
      - RUST_BACKTRACE=1
    ports:
      - '8080:8080'
    depends_on:
      - db
volumes:
  my-db: