//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "PetLocation")]
pub struct Model {
    #[sea_orm(column_name = "PetID", primary_key, auto_increment = false)]
    pub pet_id: i32,
    #[sea_orm(column_name = "Latitude", column_type = "Float")]
    pub latitude: f32,
    #[sea_orm(column_name = "Longitude", column_type = "Float")]
    pub longitude: f32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::pets::Entity",
        from = "Column::PetId",
        to = "super::pets::Column::PetId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Pets,
}

impl Related<super::pets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Pets.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
