//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "PetLocation")]
pub struct Model {
    #[sea_orm(column_name = "CatID", primary_key, auto_increment = false)]
    pub cat_id: i32,
    #[sea_orm(column_name = "Latitude", column_type = "Float")]
    pub latitude: f32,
    #[sea_orm(column_name = "Longitude", column_type = "Float")]
    pub longitude: f32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::cat::Entity",
        from = "Column::CatId",
        to = "super::cat::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Cat,
}

impl Related<super::cat::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Cat.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
