//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

pub use super::owners::Entity as Owners;
pub use super::pet_location::Entity as PetLocation;
pub use super::pets::Entity as Pets;
pub use super::pets_by_owners::Entity as PetsByOwners;
