//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

pub use super::cat::Entity as Cat;
pub use super::pet_location::Entity as PetLocation;
pub use super::user::Entity as User;
pub use super::user_pet::Entity as UserPet;
