//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

pub use super::pet_location::Entity as PetLocation;
pub use super::pets::Entity as Pets;
pub use super::user_pets::Entity as UserPets;
pub use super::users::Entity as Users;
