//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "UserPet")]
pub struct Model {
    #[sea_orm(column_name = "CatID", primary_key, auto_increment = false)]
    pub cat_id: i32,
    #[sea_orm(column_name = "UserID", primary_key, auto_increment = false)]
    pub user_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::cat::Entity",
        from = "Column::CatId",
        to = "super::cat::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Cat,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    User,
}

impl Related<super::cat::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Cat.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
